# -*- coding: utf-8 -*-
"""To-Do-List.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mm4773HQBPeRagKUAoKaP49k1x0f1S6n
"""

tasks = []

def add_task():
    title = input("Enter task title: ")
    tasks.append({'title': title, 'completed': False})
    print("Task added successfully!")

def view_tasks():
    if not tasks:
        print("No tasks found.")
    for idx, task in enumerate(tasks):
        status = "Done" if task['completed'] else "Pending"
        print(f"{idx + 1}. {task['title']} - {status}")

def update_task():
    view_tasks()
    task_no = int(input("Enter task number to update: ")) - 1
    if 0 <= task_no < len(tasks):
        new_title = input("Enter new title: ")
        tasks[task_no]['title'] = new_title
        print("Task updated successfully!")
    else:
        print("Invalid task number.")

def delete_task():
    view_tasks()
    task_no = int(input("Enter task number to delete: ")) - 1
    if 0 <= task_no < len(tasks):
        tasks.pop(task_no)
        print("Task deleted successfully!")
    else:
        print("Invalid task number.")

def mark_completed():
    view_tasks()
    task_no = int(input("Enter task number to mark as completed: ")) - 1
    if 0 <= task_no < len(tasks):
        tasks[task_no]['completed'] = True
        print("Task marked as completed!")
    else:
        print("Invalid task number.")

# Run the To-Do list app
while True:
    print("\n=== TO-DO LIST MENU ===")
    print("1. Add Task")
    print("2. View Tasks")
    print("3. Update Task")
    print("4. Delete Task")
    print("5. Mark Task as Completed")
    print("6. Exit")
    choice = input("Enter your choice: ")

    if choice == '1':
        add_task()
    elif choice == '2':
        view_tasks()
    elif choice == '3':
        update_task()
    elif choice == '4':
        delete_task()
    elif choice == '5':
        mark_completed()
    elif choice == '6':
        print("Exiting To-Do List App.")
        break
    else:
        print("Invalid choice. Try again.")

